name: Build
on: [ pull_request, push, workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v5
      - name: Setup JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: 'zulu'
          cache: gradle
      - name: Make gradle wrapper executable
        working-directory: backend
        run: chmod +x ./gradlew
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Setup Node packages
        run: npm ci --prefix frontend
      - name: Lint files
        run: npm run lint --prefix frontend
      - name: Test project
        run: npm run test --watch=false --prefix frontend
      - name: Build project
        run: npm run build --prefix frontend
      - name: Build Groovy
        working-directory: backend
        run: ./gradlew build --no-daemon
      - name: Capture main build artifact
        uses: actions/upload-artifact@v4
        with:
          name: Main
          path: backend/build/libs/
